[package]
name = "chinese-lunisolar-calendar"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/chinese-lunisolar-calendar"
homepage = "https://magiclen.org/chinese-lunisolar-calendar"
keywords = ["chinese", "calendar", "lunar", "leap", "solar"]
categories = ["localization"]
description= ""
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/chinese-number", branch = "master" }
appveyor = { repository = "magiclen/chinese-number", branch = "master", service = "github" }

[dependencies]
chrono = "0.4.6"
lazy_static = "1.2.0"
chinese-variant = "1.0.1"